---

#- fail: msg="This role is only compatible with Ubuntu"
#  when: ansible_distribution != 'Ubuntu'

- name: Include version-specific variables for Ubuntu.
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
  when: ansible_os_family == 'Debian'
- name: Include version-specific variables for RedHat
  include_vars: "RedHat-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_os_family == "RedHat"
#- name: Include version-specific variables for Alpine
#  include_vars: "Alpine.yml"
#  when: ansible_os_family == "Alpine"

- include: zentral.yml

